name: Sephsson
favicon: null
layout_spectrum: 0.3209331864491105
typography_spectrum: 0.34697881271131337
title: SEPHSSON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#bbc0c4'
    - '#000000'
    - '#937050'
    - '#343338'
  brandStrength: 0.9502572463825345
  lightness: 0.21740379044786096
  saturation: 0.8386079918127507
  rhythmicContrast: 0.15821878775022924
purpose: []
